name: validation pipeline

on:
  workflow_dispatch:
  push:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  PYTHON_VERSION: '3.12'

jobs:
  Linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install flake8 linter
        run: |
          python -m pip install pip
          pip install flake8==7.1.1 nbqa==1.9.0 flake8-todos==0.3.1

      - name: Run flake on py files
        run: flake8 --max-line-length=120 --statistics --ignore E127,E402,E731,E741,W503,T002 .

      - name: Run flake on notebook files
        run: nbqa flake8 . --max-line-length=120 --statistics --ignore E127,E402,E731,E741,W503,T002 --nbqa-exclude=third_party

